dist: trusty
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
language: node_js
node_js:
- '12'
cache:
  yarn: true
  directories:
  - node_modules
deploy:
- provider: script
  script: bin/build.sh
  skip_cleanup: true
  on:
    tags: true
    branch: master
env:
  global:
  - secure: ILO8ZNQWS3tGxHOAmA029YycGLVrEgPudqMCHnw5Ni7rkjTT4/zUZLOGTM1lPFQ31cfM3/i3pI+DMAb9bV6c6Hm1gqAHvY8f8TPNMEdvfXul96ICiQpazL6j9vPpm3c2aqz7aHFlIpQveb9S4rvMwLmFVP+M9qsIt69r9oqXlsR4fJIX3OAt4XVKH4htlRZixWIJgo1tqh7ic9kWwWxDlqI9DzKFWNeIFs2FxtOQTNBG2YuD+esehx7rkcm8ihSnuSPoiSn+kyfdeq54DK8IR2n8BgqIeSWGmAfCLaHcC5d0R1huSIC9wteVL5e8/No/zfL+PVriSMOdM/n+zK+D9XZTHBrLzr9mgozBrBlNp7Qc0DanO3NotFcjLV4y1HOuV4PkqGO1kyV8F3AyPEa7mRPJMJhg5n4wofbdhi9nkynOoqGgFa+FyYp9rAH01qp1HdphEyMeL+1/ADRhTI/wBtlafr95NkJ7E5M0i5BSVvO0WFOUWREI1jjdlh6HbU5elRbw6TRQTthD47baoiA4KqRtTLkz3Tz6Qk5nzas5yuHZHUYesHTrEVH047+noGEpd642bkEZ6XsjPQ/z1TzGpoodRaUjeoyeD04LGTWD/2WjF/74RzY+/pwqFxK+LadoytIJjAWI7kqfqXpL3urQ7mRUkR45nzVbxaBPV4UrWE0=
